name: PR Security Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Secret Scanning
      - name: Secret Scan (Gitleaks OSS)
        continue-on-error: true
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          ./gitleaks detect --verbose . --report-format json --report-path gitleaks-report.json --no-banner --exit-code 1
          cat gitleaks-report.json
      # SAST for JS/TS/JSX
      - name: Static Analysis (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
         config: "p/owasp-top-ten"
         
      # Install backend dependencies
      - name: Install Backend
        run: |
          cd firebase/backend
          npm install
    
      # Install frontend dependencies
      - name: Install Frontend
        run: |
          cd firebase/frontend
          npm install
      # SCA (Trivy filesystem scan)
      - name: Dependency Scan Backend
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          dir: ./backend
          severity: HIGH,CRITICAL

      - name: Dependency Scan Frontend
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          dir: ./frontend
          severity: HIGH,CRITICAL
